export const DISH_TYPES = ['entree', 'plat', 'dessert'] as const;
export const CUISINE_TYPES = [
  'thai',
  'indien',
  'francais',
  'italien',
  'japonais',
  'mexicain',
  'chinois',
  'grec',
  'libanais',
  'marocain',
  'vietnamien',
  'espagnol',
  'portugais',
  'indonesien',
  'coreen',
  'turc',
  'americain',
  'britannique',
] as const;
export const DIET_TYPES = [
  'vegetarien',
  'vegan',
  'sans_gluten',
  'sans_lactose',
  'sans_oeufs',
  'proteine',
  'low_carb',
  'paleo',
  'keto',
  'halal',
  'casher',
] as const;
